# Topsis

In [275]:
# Number of columns, number of weights and number of impacts should be same before proceeding

# importing libraries
import pandas as pd
import numpy as np
import math as m

In [276]:
# importing dataset
dataset = pd.read_csv('data.csv')
dataset = dataset.iloc[:,1:].values
row, col = dataset.shape
print(dataset)
print("Shape : {}x{}".format(row, col))

# for converting into dataframe
# dt = pd.DataFrame(dataset)

[[15 19  4  9  2]
 [ 8 11  3  2  4]
 [ 6  9 10 18 13]
 [12  4 20  9 18]
 [11 13 11 10 13]]
Shape : 5x5


In [277]:
# defining weights
# should only increase if number of columns increase
w = [1, 6, 1, 2, 1]

In [279]:
# Step 1 => calculating normalized matrix
sumOfSquares = []
for j in range(0, col):
    sum = 0
    for i in range(0, row):
        value = dataset[i][j]
        sum = sum + m.pow(value,2)
    sqrtOfSum = m.sqrt(sum)
    sqrtOfSum = round(sqrtOfSum, 4)
    sumOfSquares.append(sqrtOfSum)
print('Column-wise root of sum of squares', sumOfSquares)

# creating a new 2D array
dataset2 = [[0 for i in range(col)] for j in range(row)] 

# dividing by the respected values
for j in range(0, col):
    for i in range(0, row):
        temp = dataset[i][j]/sumOfSquares[j]
        dataset2[i][j] = round(temp, 4)

print('normalized matrix')
print(np.matrix(dataset2))

Column-wise root of sum of squares [24.2899, 27.3496, 25.4165, 24.2899, 26.1151]
normalized matrix
[[0.6175 0.6947 0.1574 0.3705 0.0766]
 [0.3294 0.4022 0.118  0.0823 0.1532]
 [0.247  0.3291 0.3934 0.741  0.4978]
 [0.494  0.1463 0.7869 0.3705 0.6893]
 [0.4529 0.4753 0.4328 0.4117 0.4978]]


In [280]:
# Step 2 => calculating weighted normalized matrix
for j in range(0, col):
    for i in range(0, row):
        temp2 = dataset2[i][j]*w[j]
        dataset2[i][j] = round(temp2, 4)

print('weighted normalized matrix')
print(np.matrix(dataset2))

weighted normalized matrix
[[0.6175 4.1682 0.1574 0.741  0.0766]
 [0.3294 2.4132 0.118  0.1646 0.1532]
 [0.247  1.9746 0.3934 1.482  0.4978]
 [0.494  0.8778 0.7869 0.741  0.6893]
 [0.4529 2.8518 0.4328 0.8234 0.4978]]


In [281]:
# Step 3 => calculating ideal best and ideal worst
# length of impacts should only increase if number of coulmns increase
impacts = ['+', '+', '-', '+', '-']

bestValues = []
worstValues = []

dataset3 = pd.DataFrame(dataset2)
maxValues = dataset3.max()
minValues = dataset3.min()

for num in range(0, len(impacts)):
    if impacts[num] == '+':
        bestValues.append(maxValues[num])
        worstValues.append(minValues[num])
    else:
        bestValues.append(minValues[num])
        worstValues.append(maxValues[num])

# should only increase if number of columns increase
print('Ideal Best Values (r)\n', bestValues)
# print('')
print('Ideal Worst Values (r)\n', worstValues)

Ideal Best Values (r)
 [0.6175, 4.1682, 0.118, 1.482, 0.0766]
Ideal Worst Values (r)
 [0.247, 0.8778, 0.7869, 0.1646, 0.6893]


In [282]:
# Step 4 => calculating euclidean distance from ideal bests and ideal worsts
SPlus = []
SMinus = []

# print(dataset2)

for i in range(0, row):
    bestSum = 0
    worstSum = 0
    for j in range(0, col):
        bestSum = bestSum + m.pow((dataset2[i][j]-bestValues[j]),2)
        worstSum = worstSum + m.pow((dataset2[i][j]-worstValues[j]), 2)
    SPlus.append(round(m.sqrt(bestSum), 4))
    SMinus.append(round(m.sqrt(worstSum), 4))
    
# should only increase if number of rows increase
print('SPlus (c)\n', SPlus)
# print('')
print('SMinus (c)\n', SMinus)

SPlus (c)
 [0.742, 2.2146, 2.2809, 3.4948, 1.5717]
SMinus (c)
 [3.4739, 1.7604, 1.7692, 0.6271, 2.1296]


In [283]:
# Step 5 => calculating performance score
pi = []
for index in range(0, row):
    pi.append(round(SMinus[index] / (SMinus[index] + SPlus[index]), 4))

# should only increase if number of rows increase
print('Performance Score (c)\n', pi)

Performance Score (c)
 [0.824, 0.4429, 0.4368, 0.1521, 0.5754]


In [284]:
# Step 6 => calculating rank
rank = []
sortedPi = sorted(pi, reverse = True)

for x in range(0, len(pi)):
    for y in range(0, len(sortedPi)):
        if pi[x] == sortedPi[y]:
            rank.append(y+1)
            
# should only increase if number of rows increase
print('Performance Score (c)\n', pi)
# print('Performance Score (in decreased order)\n', sortedPi)
print('Rank (c)\n', rank)

Performance Score (c)
 [0.824, 0.4429, 0.4368, 0.1521, 0.5754]
Rank (c)
 [1, 3, 4, 5, 2]
